version: "3.7"
services:

  postgres:
    image: ghcr.io/open-discourse/open-discourse/database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    networks:
      - network-backend

volumes:
  postgres_data:

networks:
  network-backend:


